source 'http://rubygems.org'

gem 'guard'
gem 'guard-shell'
gem 'rb-inotify'
gem 'guard-livereload'
gem 'yajl-ruby'
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'tilt'
gem 'slim'
gem 'rake'
