= Microservice everything 
Jakub Marchwicki ; @kubem 
:longform:
:sectids!:
:imagesdir: images
:source-highlighter: highlightjs
:language: no-highlight
:dzslides-aspect: 16-9
:dzslides-style: stormy-jm
:dzslides-transition: fade
:dzslides-fonts: family=Yanone+Kaffeesatz:400,700,200,300&family=Cedarville+Cursive
:dzslides-highlight: monokai
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font

[.topic]
== Who is this guy?

[.statement]
As it that made any *difference*

[.topic]
== Things to cover

[.incremental]
* What is microservice?
* Why bother? 
* Why I cared?
* How I cared?
* Was it worth doing?


[.topic]
== Agenda

* *What is microservice?*
* Why bother? 
* Why I cared?
* How I cared?
* Was it worth doing?

== !

[.middle]
Micro Service is an *architectural concept* that aims to decouple a solution by decomposing functionality into discrete services +
[detail]#with communication over lightweight mechanisms, often an HTTP API#

[NOTE]
[role="speaker"]
====
* this means everything
* maybe a diagram will go better
====

[role="terminal"]
== !

....



       +----------------------------------+                                    
       |                                  |                        ++          
       |  +--------------------+  +----+  |               +---+    ++          
       |  |                    |  |    |  |               |   |                
       |  |                    |  |    |  |               |   |  +--------+    
       |  +--------------------+  |    |  |               +---+  |        |    
       |                          |    |  |                      |        |    
       |  +-----+  +-----+ +---+  |    |  |            +-+       |        |    
       |  |     |  |     | |   |  |    |  |            +-+  +-+  +--------+    
       |  |     |  |     | |   |  |    |  |                 +-+                
       |  +-----+  +-----+ +---+  |    |  |         +----+           +--+      
       |                          |    |  |         |    |  +----+   |  |      
       |  +--------------------+  |    |  |         +----+  |    |   +--+  +--+
       |  |                    |  |    |  |                 |    |         |  |
       |  |                    |  |    |  |            +-+  +----+         +--+
       |  +--------------------+  +----+  |            +-+          +---+      
       |                                  |                         |   |      
       +----------------------------------+                         +---+      
                                                                        
                                                                        
              Monolythic / layered                           Microservice      

....

[.topic]
== My personal definition

[.incremental]
* A small problem domain [detail]#Bounded Content might be the thing#
* Built and deployed by itself [detail]#standalone and isolated#
* Runs in its own process
* Integrates via well-known interfaces + 
[detail]#While HTTP isn’t always the best answer, it’s a damn fine first guess#
* Owns its own data storage [detail]#ultimate goal#

[.topic]
== Agenda

* What is microservice?
* *Why bother?*
* Why I cared?
* How I cared?
* Was it worth doing?

[.topic]
== Modularity at all levels

[.incremental]
* Function 
* Object 
* Class 
* Actor 
* Stream transform 
* *Microservice* 

[NOTE]
[role="speaker"]
====
* Pointed out by Martin Odersky at GOTOchicago
* Single Responsibility Principle  taken to an extreme
====


== !
[.statement]
*SOA* done right?

[NOTE]
[role="speaker"]
====
* 15 years since the concept of Service Oriented Architecture
* significant changes in the way we think about architecture
====

== !
[.statement]
*Aggregates* and bounded *Contexts* give us a great way of breaking up a domain

[NOTE]
[role="speaker"]
====
* Eric Evan’s - Domain Driven Design
* Service interface between each context
* ensure a service is responsible for an aggregate root and all of it’s child domain objects
====

== !
[.statement]
*REST* style interfaces and *JSON* as a data interchange

== !
[.statement]
Build *web services* + 
easier than ever with +
*micro* frameworks

[NOTE]
[role="speaker"]
====
* In JAVA world count: 
** Simple embedded Jetty, 
** Spark, Webbit, Dropwizard
** Vert.x, Spring Boot
====

[.topic]
== Agenda

* What is microservice?
* Why bother?
* *Why I cared?*
* How I cared?
* Was it worth doing?

[.topic]
== The beshitted legacy system 

[.incremental]
* an interesting application in legacy systems
* don't touch it approach [detail]#as if you meant it#
* write a small service that does what's needed +
[detail]#instead of diving into legacy system#
* an architecture evolution

[NOTE]
[role="speaker"]
====
* Working with legacy code is risky at best
* We all know it
====


[role="terminal"]
== !
....
        Legacy system                             
                                                                                      
+------------------------------+                      
|                              |                                 
|   +----------------------+   |                                
|   |                      |   |                               
|   |                      | <-------------------------------------------------------+
|   |                      |   |                              
|   +----------------------+   |                             
|         +       +-------+    |                            
|         |       |       |    |                           
|         |       |       |    |                          
|         |       +-------+    |                         
|         |       +-------+    |                        
|         |       |       |    |                       
|         |       |       |    |                      
|         |       +-------+    |                     
|         |                    |                    
+------------------------------++                  
          |                      
          v                      
+------------------------------+ 
|                              |
|                              | 
|                              |                                                      
+------------------------------+                                                      
                                                                                      
            Database                                                                  
....


[role="terminal"]
== !
....
        Legacy system                                               Proxy             
                                                                                      
+------------------------------+                                   +------+           
|                              |                                   |      |           
|   +----------------------+   |                                   |      |           
|   |                      |   |                                   |      |           
|   |                      | <-------------------------------------------------------+
|   |                      |   |                                   |      |           
|   +----------------------+   |                                   |      |           
|         +       +-------+    |                                   |      |           
|         |       |       |    |                                   |      |           
|         |       |       |    |                                   |      |           
|         |       +-------+    |                                   |      |           
|         |                    |              +-------+            |      |           
|         |                    |              |       |            |      |           
|         |                    |              |       | <----------------------------+
|         |                    |              |       |            |      |           
|         |                    |              +-------+            |      |           
+------------------------------+                  +                +------+           
          |                                       |                                   
          v                                       |                                   
+------------------------------+                  |                                   
|                              |                  |                                   
|                              | <----------------+                                   
|                              |                                                      
+------------------------------+                                                      
                                                                                      
            Database                                                                  
....

[.topic]

== Some problems with monolythic architecture

[.incremental]
* Even when layered, hidden coupling
* Single runtime, allows in memory calls
* FUD: if it works don't fix it [detail]#don't touch it# 
* Good diagrams not always make it to good code

[NOTE]
[role="speaker"]
====
* I know this might not always be true
** Though it usually happens
* 
====


[.topic]
== Agenda

* What is microservice?
* Why bother?
* Why I cared?
* *How I cared?*
* Was it worth doing?


[.topic.recap]
== Exibit A

[.statement.pull-right]
a mysterious scoring engine [detail]#-- 2007#

[.topic]
== Agenda

* What is microservice?
* Why bother?
* Why I cared?
* How I cared?
* *Was it worth doing?*

== !

[.statement]
Still *don't* know

[NOTE]
[role="speaker"]
====
* it's hard to say. architecture decisions does not pay off quickly (usually)
* in some causes that was the only way to go
* We haven't really touched on operations, deploying small thingies
** In many cases it's a component cased architecture
====


[role="terminal"]
== !

....


       +----------------------------------+                                    
       |                                  |                        ++          
       |  +--------------------+  +----+  |               +---+    ++          
       |  |                    |  |    |  |               |   |                
       |  |                    |  |    |  |               |   |  +--------+    
       |  +--------------------+  |    |  |               +---+  |        |    
       |                          |    |  |                      |        |    
       |  +-----+  +-----+ +---+  |    |  |            +-+       |        |    
       |  |     |  |     | |   |  |    |  |            +-+  +-+  +--------+    
       |  |     |  |     | |   |  |    |  |                 +-+                
       |  +-----+  +-----+ +---+  |    |  |         +----+           +--+      
       |                          |    |  |         |    |  +----+   |  |      
       |  +--------------------+  |    |  |         +----+  |    |   +--+  +--+
       |  |                    |  |    |  |                 |    |         |  |
       |  |                    |  |    |  |            +-+  +----+         +--+
       |  +--------------------+  +----+  |            +-+          +---+      
       |                                  |                         |   |      
       |                                  |                         +---+
       +----------------------------------+                        
                                                                        
                                                                        
              Monolythic / layered                           Microservice      

....


[role="terminal"]
== !

....


       +----------------------------------+      +--------------------------------+                              
       |                                  |      |                 ++             |
       |  +--------------------+  +----+  |      |        +---+    ++             |
       |  |                    |  |    |  |      |        |   |                   |
       |  |                    |  |    |  |      |        |   |  +--------+       |
       |  +--------------------+  |    |  |      |        +---+  |        |       |
       |                          |    |  |      |               |        |       |
       |  +-----+  +-----+ +---+  |    |  |      |     +-+       |        |       |
       |  |     |  |     | |   |  |    |  |      |     +-+  +-+  +--------+       |
       |  |     |  |     | |   |  |    |  |      |          +-+                   |
       |  +-----+  +-----+ +---+  |    |  |      |  +----+           +--+         |
       |                          |    |  |      |  |    |  +----+   |  |         |
       |  +--------------------+  |    |  |      |  +----+  |    |   +--+  +--+   |
       |  |                    |  |    |  |      |          |    |         |  |   |
       |  |                    |  |    |  |      |     +-+  +----+         +--+   |
       |  +--------------------+  +----+  |      |     +-+          +---+         |
       |                                  |      |                  |   |         |
       |                                  |      |                  +---+         |
       +----------------------------------+      +--------------------------------+
                                                                        
                                                                        
              Monolythic / layered                      Something in between 
                                                           (components ?)    

....

[NOTE]
[role="speaker"]
====
* easier to handle by operations
* easier to spoil, couple elements through internal calls
** HTTP is pretty ruthless - you can't bypass
** You can call different component within 
====

== !

[.small.quote, James Lewis]
____
We define *libraries* as components that are linked into a program and called using in-memory calls, while *services* are out-of-process components who communicate with remote procedure calls 
____

[NOTE]
[role="speaker"]
====
* So this might be a problem
** Awareness, code reviews and inspections are important
====


== !

[.small.quote, James Lewis]
____
Microservice applications put a lot of emphasis on *real-time monitoring* of the application, checking both architectural elements and business relevant metrics
____

[NOTE]
[role="speaker"]
====
* Monitoring beyond Naigos
** We are still not very good in it, still learing
* Business metrics are very hard to grasp with `business at the other side of the wall`
====

== !

[.statement]
But we are still *trying*

[.topic.ending, hrole="name"]
== Questions?

[.footer]
[icon-twitter]'{zwsp}' @kubem


[.topic]
== Useful links and some notes

[.middle]
----
http://speakerdeck.com/kubamarchwicki/microservice-everything

Further reading material
  http://readlists.com/14bb4629/

Sam Newman - Building Microservices
  http://shop.oreilly.com/product/0636920033158.do

This presentation was made with Asciidoctor
  http://asciidoctor.org/

Tools when preparing this slides
  http://paulrouget.com/dzslides/
  http://asciiflow.com/
----

