= Java Enterprise'ish development with hassle

This happens in every community: You don’t need Rails, to build a web application in Ruby. You don’t need templating engine for PHP - PHP is a templating language! We over engineer and over engineer, again and again.
Same happens in Java. Hibernate + EJB + JSF is not the only blessed stack for development of web application… one can argue it’s the worst. Same with Spring; no longer lighweight, no so robust - still powerful but not necessary the easiest. So what are the options for an average Java developer?
In this talk I’ll walk through multiple options, for modern Java web development: easy, quick, flexible and still state of an art. Starting for just obvious unknowns like embedded jetty, though micro pure-webframeworks, smaller and bigger swiss army knifes, which try to promise both: cover most of the application stack, still keeping things robust.

https://htmlpreview.github.io/?https://github.com/kubamarchwicki/presentations/master/jee-without-hassle/slides-pl.html[HTML slides]
https://speakerdeck.com/kubamarchwicki/jee-without-hassle-pl[PDF slides (at) speakerdeck]

== Presented at:

* 2014-07-05 Confitura 2014 - Warsaw
